---
platform: linux
params:
  OM_USERNAME: 
  OM_PASSWORD: 
  OM_DECRYPTION_PASSPHRASE: 
  OM_SKIP_SSL_VALIDATION: 
image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/releng-tools
    tag: latest
inputs:
- name: terraform-state
- name: config
outputs:
- name: env
run:
  path: bash
  args: 
  - -c
  - |
    set -eo pipefail
    ./config/config/director/create-env.sh > env/env.yml