product-name: cf
product-properties:
  .cloud_controller.system_domain:
    value: ((system_domain))
  .cloud_controller.apps_domain:
    value: ((apps_domain))
  .properties.routing_tls_termination:
    value: router
  .properties.haproxy_forward_tls:
    value: disable
  .ha_proxy.skip_cert_verify:
    value: true
  .properties.networking_poe_ssl_certs:
    value:
    - name: pas-wildcard
      certificate:
        cert_pem: ((cert_pem))
        private_key_pem: ((key_pem))
  .properties.logger_endpoint_port:
    value: 443
  .properties.experimental_dynamic_egress_enforcement
    value: 1
  .properties.security_acknowledgement:
    value: X
  .properties.secure_service_instance_credentials:
    value: true
  .properties.cf_networking_enable_space_developer_self_service:
    value: true
  .uaa.service_provider_key_credentials:
    value:
      cert_pem: ((cert_pem))
      private_key_pem: ((key_pem))
  .properties.credhub_key_encryption_passwords:
    value: 
    - name: key1
      key: 
        secret: credhubsecret1credhubsecret1
      primary: true
  .mysql_monitor.recipient_email:
    value: notify@example.com
  .properties.system_database:
    value: external
  .properties.system_database.external.host:
    value: ((rds_address))
  .properties.system_database.external.port:
    value: ((rds_port))
  .properties.system_database.external.app_usage_service_username:
    value: ((rds_username))
  .properties.system_database.external.app_usage_service_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.autoscale_username:
    value: ((rds_username))
  .properties.system_database.external.autoscale_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.ccdb_username:
    value: ((rds_username))
  .properties.system_database.external.ccdb_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.diego_username:
    value: ((rds_username))
  .properties.system_database.external.diego_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.locket_username:
    value: ((rds_username))
  .properties.system_database.external.locket_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.networkpolicyserver_username:
    value: ((rds_username))
  .properties.system_database.external.networkpolicyserver_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.nfsvolume_username:
    value: ((rds_username))
  .properties.system_database.external.nfsvolume_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.notifications_username:
    value: ((rds_username))
  .properties.system_database.external.notifications_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.account_username:
    value: ((rds_username))
  .properties.system_database.external.account_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.routing_username:
    value: ((rds_username))
  .properties.system_database.external.routing_password:
    value: 
      secret: ((rds_password))
  .properties.system_database.external.silk_username:
    value: ((rds_username))
  .properties.system_database.external.silk_password:
    value: 
      secret: ((rds_password))
  .properties.uaa_database:
    value: external
  .properties.uaa_database.external.host:
    value: ((rds_address))
  .properties.uaa_database.external.port:
    value: ((rds_port))
  .properties.uaa_database.external.uaa_username:
    value: ((rds_username))
  .properties.uaa_database.external.uaa_password:
    value: 
      secret: ((rds_password))
  .properties.credhub_database:
    value: external
  .properties.credhub_database.external.host:
    value: ((rds_address))
  .properties.credhub_database.external.port:
    value: ((rds_port))
  .properties.credhub_database.external.username:
    value: ((rds_username))
  .properties.credhub_database.external.password:
    value: 
      secret: ((rds_password))
  .properties.credhub_database.external.tls_ca:
    value:  ((rds_ca))
  .properties.system_blobstore:
    value: external
  .properties.system_blobstore.external.endpoint:
    value: ((s3_endpoint))
  .properties.system_blobstore.external.access_key:
    value: ((access_key_id))
  .properties.system_blobstore.external.secret_key:
    value: 
      secret: "((secret_access_key))"
  .properties.system_blobstore.external.signature_version:
    value: 4
  .properties.system_blobstore.external.region:
    value: ((s3_region))
  .properties.system_blobstore.external.buildpacks_bucket:
    value: ((pas_buildpacks_bucket))
  .properties.system_blobstore.external.droplets_bucket:
    value: ((pas_droplets_bucket))
  .properties.system_blobstore.external.packages_bucket:
    value: ((pas_packages_bucket))
  .properties.system_blobstore.external.resources_bucket:
    value: ((pas_resources_bucket))
  .properties.autoscale_instance_count:
    value: 1
  .properties.smtp_from:
    value: ((smtp_from))
  .properties.smtp_address:
    value: ((smtp_address))
  .properties.smtp_port:
    value: ((smtp_port))
  .properties.smtp_credentials:
    value:
      identity: ((smtp_username))
      password: ((smtp_password))
  .properties.smtp_enable_starttls_auto:
    value: ((smtp_enable_starttls))
network-properties:
  network:
    name: ((pas_main_network_name))
  service_network:
    name: ((pas_services_network_name))
  other_availability_zones: ((availability_zones))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
resource-config:
  database:
    instances: 1
    instance_type:
      id: m4.large
    additional_vm_extensions:
    - spot-instance-m4-large
  blobstore:
    instances: 0
    instance_type:
      id: t2.medium
    additional_vm_extensions:
    - spot-instance-t2-medium
  control:
    instances: 1
    instance_type:
      id: m4.xlarge
    additional_vm_extensions:
    - spot-instance-m4-xlarge
  compute:
    instances: 1
    instance_type:
      id: r4.xlarge
    additional_vm_extensions:
    - spot-instance-r4-xlarge
  backup_restore:
    instances: 0
    instance_type:
      id: t2.micro
    additional_vm_extensions:
    - spot-instance-t2-micro
  ha_proxy:
    instances: 0
    instance_type:
      id: t2.micro
    additional_vm_extensions:
    - spot-instance-t2-micro
  router:
    instances: 1
    instance_type:
      id: t2.micro
    additional_vm_extensions:
    - spot-instance-t2-micro
  mysql_monitor:
    instances: 0
    instance_type:
      id: t2.micro
    additional_vm_extensions:
    - spot-instance-t2-micro
  tcp_router:
    instances: 1
    instance_type:
      id: t2.micro
    additional_vm_extensions:
    - spot-instance-t2-micro
